<?php

$g_DefaultLang = "en";
$g_Loc = array(
	//------------------------------------------------------------------------- ENGLISH
    "en" => array(
		"language"						=> "English",
		
		"date.lang"						=> "en",
		"date.format.short"				=> "%#d %B",
		"date.format.med"				=> "%#d %B %Y",
		"date.format.full"				=> "%A, %#d %B %Y",
		"date.day.0"					=> "sunday",
		"date.day.1"					=> "monday",
		"date.day.2"					=> "tuesday",
		"date.day.3"					=> "wednesday",
		"date.day.4"					=> "thursday",
		"date.day.5"					=> "friday",
		"date.day.6"					=> "saturday",
		"date.month.1"					=> "january",
		"date.month.2"					=> "february",
		"date.month.3"					=> "march",
		"date.month.4"					=> "april",
		"date.month.5"					=> "may",
		"date.month.6"					=> "june",
		"date.month.7"					=> "july",
		"date.month.8"					=> "august",
		"date.month.9"					=> "september",
		"date.month.10"					=> "october",
		"date.month.11"					=> "november",
		"date.month.12"					=> "december",

		"system.confirm"				=> "Are you sure?",

		"page.map"						=> "Map",
		"page.crops"					=> "Crops",
		"page.collection"				=> "Collection",
		"page.schedule"					=> "Schedule",
		"page.project"					=> "Project",
		"page.user"						=> "User",
		
		// `variety` table
        "variety.id"					=> "ID",
        "variety.name"					=> "Name",
        "variety.name_latin"			=> "Scientific name",
        "variety.category"				=> "Category",
        "variety.type"					=> "Type",
        "variety.image"					=> "Image",
        "variety.exposure"				=> "Exposure",
        "variety.height"				=> "Height",
        "variety.width"					=> "Width",
        "variety.emergence"				=> "Emergence",
        "variety.hardiness"				=> "Hardiness",
        "variety.hardiness.info"		=> "A hardiness zone is a geographic area defined to encompass a certain range of climatic conditions relevant to plant growth and survival",
        "variety.watering"				=> "Watering",
        "variety.ph"					=> "pH",
        "variety.cycle"					=> "Cycle",
        "variety.growth"				=> "Growth",
        "variety.edible_part"			=> "Edible",
        "variety.edible_desc"			=> "Desc",
        "variety.edible_color"			=> "Color",
        "variety.edible_weight"			=> "Weight",
        "variety.edible_size"			=> "Size",
        "variety.resistance"			=> "Resistance",
        "variety.sensitivity"			=> "Sensitivity",
        "variety.pollinator"			=> "Pollinator",

		"variety.type.tree"				=> "Tree",
		"variety.type.shrub"			=> "Shrub",
		"variety.type.mushroom"			=> "Mushroom",
		"variety.type.climbing"			=> "Climbing",
		"variety.type.herbaceous"		=> "Herbaceous",
		"variety.type.root"				=> "Root",
		"variety.type.trailing"			=> "Trailing",
		
		"variety.exposure.fullsun"		=> "Full sun",
		"variety.exposure.partsun"		=> "Part sun",
		"variety.exposure.partshade"	=> "Part shade",
		"variety.exposure.fullshade"	=> "Full shade",
		
		"variety.watering.without"		=> "Without",
		"variety.watering.little"		=> "Little",
		"variety.watering.medium"		=> "Medium",
		"variety.watering.many"			=> "Much",
		
		"variety.cycle.annual"			=> "Annual",
		"variety.cycle.biennial"		=> "Biennial",
		"variety.cycle.vivace"			=> "Vivace",

		"variety.growth.slow"			=> "Slow",
		"variety.growth.average"		=> "Average",
		"variety.growth.fast"			=> "Fast",

		"variety.edible_part.flower"	=> "Flower",
		"variety.edible_part.fruit"		=> "Fruit",
		"variety.edible_part.root"		=> "Root",
		"variety.edible_part.walnuts"	=> "Walnuts",
		"variety.edible_part.leaf"		=> "Leaf",
		"variety.edible_part.sap"		=> "Sap",
		"variety.edible_part.seed"		=> "Seed",
		"variety.edible_part.sprout"	=> "Sprout",
		"variety.edible_part.young leaf"	=> "Young leaf",
		"variety.edible_part.stem"		=> "Stem",
		"variety.edible_part.bulb"		=> "Bulb",
		"variety.edible_part.whole"		=> "Whole",
		
		"variety.variety_period"		=> "Periods",
		
		// `variety_period` table
		"variety_period.id"				=> "ID",
		"variety_period.variety"		=> "Variety",
		"variety_period.type"			=> "Type",
		"variety_period.date_start"		=> "Start",
		"variety_period.date_end"		=> "End",
		"variety_period.color"			=> "Color",

		"variety_period.type.sowing_bucket"	=> "Sowing (pot)",
		"variety_period.type.sowing_ground"	=> "Sowing (ground)",
		"variety_period.type.conservation"	=> "Conservation",
		"variety_period.type.harvest"		=> "Harvest",
		"variety_period.type.plantation"	=> "Plantation",
		"variety_period.type.flowering"		=> "Flowering",
		"variety_period.type.pruning"		=> "Pruning",

		// `crop` table
		"crop.id"						=> "ID",
		"crop.name"						=> "Name",
		"crop.variety"					=> "Variety",
		"crop.loc_type"					=> "Localisation",
		"crop.loc_unit"					=> "Unit",
		"crop.loc_pos"					=> "Position 1",
		"crop.loc_pos2"					=> "Position 2",
		
		"crop.loc_type.point"			=> "Point",
		"crop.loc_type.circle"			=> "Circle",
		"crop.loc_type.rectangle"		=> "Rectange",
		
		"crop.loc_unit.pixel"			=> "Pixel",
		"crop.loc_unit.coordinate"		=> "Coordinate",
		
		"crop.crop_event"				=> "Events",
		
		// `crop_event` table
		"crop_event.id"					=> "ID",
		"crop_event.crop"				=> "Crop",
		"crop_event.type"				=> "Type",
		"crop_event.date"				=> "Date",
		
		"crop_event.type.sowing_bucket"	=> "Sowing (pot)",
		"crop_event.type.sowing_ground"	=> "Sowing (ground)",
		"crop_event.type.conservation"	=> "Conservation",
		"crop_event.type.harvest"		=> "Harvest",
		"crop_event.type.plantation"	=> "Plantation",
		"crop_event.type.flowering"		=> "Flowering",
		"crop_event.type.pruning"		=> "Pruning",
		
		// `project` table
		"project.id"					=> "ID",
		"project.name"					=> "Name",
		"project.lang"					=> "Language",
		"project.map_image"				=> "Map",
		"project.map_marker1_pixel"		=> "Point 1",
		"project.map_marker1_coordinate"	=> "Coordinate 1",
		"project.map_marker2_pixel"		=> "Point 2",
		"project.map_marker2_coordinate"	=> "Coordinate 2",
		"project.allow_edit"			=> "Allow edition",
		"project.allow_dev"				=> "Allow dev tools",
		"project.allow_register"		=> "Allow register",

		"project.lang.en"				=> "English",
		"project.lang.fr"				=> "Français",
		
		// User page
		"user.id"						=> "ID",
		"user.do_login"					=> "Login",
		"user.do_register"				=> "Register",
		"user.login"					=> "Login",
		"user.password"					=> "Password",
		"user.familyname"				=> "Family name",
		"user.firstname"				=> "First Name",
		"user.birthday"					=> "Birthday",
		"user.avatar"					=> "Avatar",
		"user.admin"					=> "Admin rights",
	),
	//------------------------------------------------------------------------- FRANCAIS
    "fr" => array(
		"language"						=> "Français",
		"date.lang"						=> array("fra", "fr_FR.UTF-8", "fr.UTF-8", "fr_FR.UTF8", "fr.UTF8"),
		"date.format.short"				=> "%#d %B",
		"date.format.med"				=> "%#d %B %Y",
		"date.format.full"				=> "%A %#d %B %Y",
		"date.day.0"					=> "dimanche",
		"date.day.1"					=> "lundi",
		"date.day.2"					=> "mardi",
		"date.day.3"					=> "mercredi",
		"date.day.4"					=> "jeudi",
		"date.day.5"					=> "vendredi",
		"date.day.6"					=> "samedi",
		"date.month.1"					=> "janvier",
		"date.month.2"					=> "février",
		"date.month.3"					=> "mars",
		"date.month.4"					=> "avril",
		"date.month.5"					=> "mai",
		"date.month.6"					=> "juin",
		"date.month.7"					=> "juillet",
		"date.month.8"					=> "août",
		"date.month.9"					=> "septembre",
		"date.month.10"					=> "octobre",
		"date.month.11"					=> "novembre",
		"date.month.12"					=> "décembre",

		"system.confirm"				=> "Êtes-vous sûr ?",

		"page.map"						=> "Carte",
		"page.crops"					=> "Culture",
		"page.collection"				=> "Collection",
		"page.schedule"					=> "Agenda",
		"page.project"					=> "Projet",
		"page.user"						=> "Utilisateur",
		
		// `variety` table
        "variety.id"					=> "ID",
        "variety.name"					=> "Nom",
        "variety.name_latin"			=> "Nom scientifique",
        "variety.category"				=> "Catégorie",
        "variety.type"					=> "Type",
        "variety.image"					=> "Image",
        "variety.exposure"				=> "Éxposition",
        "variety.height"				=> "Hauteur",
        "variety.width"					=> "Largeur",
        "variety.emergence"				=> "Levée",
        "variety.hardiness"				=> "Rusticité",
        "variety.watering"				=> "Arrosage",
        "variety.ph"					=> "pH",
        "variety.cycle"					=> "Cycle",
        "variety.growth"				=> "Croissance",
        "variety.edible_part"			=> "Commestible",
        "variety.edible_desc"			=> "Desc",
        "variety.edible_color"			=> "Couleur",
        "variety.edible_weight"			=> "Poids",
        "variety.edible_size"			=> "Taille",
        "variety.resistance"			=> "Résistance",
        "variety.sensitivity"			=> "Sensibilité",
        "variety.pollinator"			=> "Pollinisateur",

		"variety.type.tree"				=> "Arbre",
		"variety.type.shrub"			=> "Arbuste",
		"variety.type.mushroom"			=> "Champignon",
		"variety.type.climbing"			=> "Grimpante",
		"variety.type.herbaceous"		=> "Herbacée",
		"variety.type.root"				=> "Racine",
		"variety.type.trailing"			=> "Rampante",

		"variety.exposure.fullsun"		=> "Plein soleil",
		"variety.exposure.partsun"		=> "Mi-soleil",
		"variety.exposure.partshade"	=> "Mi-ombre",
		"variety.exposure.fullshade"	=> "Pleine ombre",

		"variety.watering.without"		=> "Sans",
		"variety.watering.little"		=> "Peu",
		"variety.watering.medium"		=> "Moyen",
		"variety.watering.many"			=> "Beaucoup",

		"variety.cycle.annual"			=> "Annuel",
		"variety.cycle.biennial"		=> "Bisannuel",
		"variety.cycle.vivace"			=> "Vivace",

		"variety.growth.slow"			=> "Lente",
		"variety.growth.average"		=> "Moyenne",
		"variety.growth.fast"			=> "Rapide",

		"variety.edible_part.flower"	=> "Fleur",
		"variety.edible_part.fruit"		=> "Fruit",
		"variety.edible_part.root"		=> "Racine",
		"variety.edible_part.walnuts"	=> "Noix",
		"variety.edible_part.leaf"		=> "Feuille",
		"variety.edible_part.sap"		=> "Sève",
		"variety.edible_part.seed"		=> "Graine",
		"variety.edible_part.sprout"	=> "Pousse",
		"variety.edible_part.young leaf"	=> "Jeune feuille",
		"variety.edible_part.stem"		=> "Tige",
		"variety.edible_part.bulb"		=> "Bulbe",
		"variety.edible_part.whole"		=> "Tout",
		
		"variety.variety_period"		=> "Périodes",

		// `variety_period` table
		"variety_period.id"				=> "ID",
		"variety_period.variety"		=> "Variété",
		"variety_period.type"			=> "Type",
		"variety_period.date_start"		=> "Début",
		"variety_period.date_end"		=> "Fin",
		"variety_period.color"			=> "Couleur",
		
		"variety_period.type.sowing_bucket"	=> "Semi (godet)",
		"variety_period.type.sowing_ground"	=> "Semi (pleine terre)",
		"variety_period.type.conservation"	=> "Conservation",
		"variety_period.type.harvest"		=> "Récolte",
		"variety_period.type.plantation"	=> "Plantation",
		"variety_period.type.flowering"		=> "Floraison",
		"variety_period.type.pruning"		=> "Taille",

		// `crop` table
		"crop.id"						=> "ID",
		"crop.name"						=> "Nom",
		"crop.variety"					=> "Variété",
		"crop.loc_type"					=> "Localisation",
		"crop.loc_unit"					=> "Unité",
		"crop.loc_pos"					=> "Position 1",
		"crop.loc_pos2"					=> "Position 2",
		
		"crop.loc_type.point"			=> "Point",
		"crop.loc_type.circle"			=> "Cercle",
		"crop.loc_type.rectangle"		=> "Rectange",
		
		"crop.loc_unit.pixel"			=> "Pixel",
		"crop.loc_unit.coordinate"		=> "Coordonnée",

		"crop.crop_event"				=> "Événements",

		// `crop_event` table
		"crop_event.id"					=> "ID",
		"crop_event.crop"				=> "Culture",
		"crop_event.type"				=> "Type",
		"crop_event.date"				=> "Date",

		"crop_event.type.sowing_bucket"	=> "Semi (godet)",
		"crop_event.type.sowing_ground"	=> "Semi (pleine terre)",
		"crop_event.type.conservation"	=> "Conservation",
		"crop_event.type.harvest"		=> "Récolte",
		"crop_event.type.plantation"	=> "Plantation",
		"crop_event.type.flowering"		=> "Floraison",
		"crop_event.type.pruning"		=> "Taille",

		// `project` table
		"project.id"					=> "ID",
		"project.name"					=> "Nom",
		"project.lang"					=> "Langue",
		"project.map_image"				=> "Carte",
		"project.map_marker1_pixel"		=> "Point 1",
		"project.map_marker1_coordinate"	=> "Coordonnée 1",
		"project.map_marker2_pixel"		=> "Point 2",
		"project.map_marker2_coordinate"	=> "Coordonnée 2",
		"project.allow_edit"			=> "Autorise l'édition",
		"project.allow_dev"				=> "Autorise dev tools",
		"project.allow_register"		=> "Autorise l'enregistrement",

		"project.lang.en"				=> "English",
		"project.lang.fr"				=> "Français",

		// User page
		"user.id"						=> "ID",
		"user.do_login"					=> "Connection",
		"user.do_register"				=> "Enregistrement",
		"user.login"					=> "Identifiant",
		"user.password"					=> "Mot de passe",
		"user.familyname"				=> "Nom",
		"user.firstname"				=> "Prénom",
		"user.birthday"					=> "Date de naissance",
		"user.avatar"					=> "Avatar",
		"user.admin"					=> "Droits d'admin",
    ),
);

?>


